function formatMs(ms: number) :: string:
    set {_l::d} to floor({_ms} / 86400000)
    set {_l::h} to floor(mod({_ms}, 86400000) / 3600000)
    set {_l::m} to floor(mod({_ms}, 3600000) / 60000)
    set {_l::s} to floor(mod({_ms}, 60000) / 1000)
    set {_l::ms} to mod({_ms}, 1000)
    set {_result} to ""
    loop "d", "h", "m", "s", "ms":
        if {_l::%loop-value%} is not 0:
            set {_result} to "%{_result}%%{_l::%loop-value%}%%loop-value% "
    return {_result}.trim()
